name: KiBot

on:
  push:
  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
  workflow_dispatch:

jobs:
  kibot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v6

    - uses: INTI-CMNB/KiBot@v2_k9
      with:
        config: config.kibot.yaml
        dir: output

    - name: Upload drawings
      uses: actions/upload-artifact@v6
      with:
        name: Servicetastatur-drawings-${{ github.sha }}
        path: output
