name: Render

on:
  push:
    paths: ['*.scad']
  pull_request:
    paths: ['*.scad']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openscad/openscad:latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/checkout@v6
        with:
          repository: lijon/jl_scad
          path: libraries/jl_scad

      - uses: actions/checkout@v6
        with:
          repository: BelfrySCAD/BOSL2
          path: libraries/BOSL2

      - run: cp -r libraries /usr/local/share/openscad/

      - run: mkdir render

      - run: openscad -D haelfte=TOP -o render/top.3mf -o render/top.stl case.scad

      - run: openscad -D haelfte=BOT -o render/bot.3mf -o render/bot.stl case.scad
      
      - uses: actions/upload-artifact@v6
        with:
          path: render/*
