name: Render

on:
  push:
    paths: ['*.scad']
  pull_request:
    paths: ['*.scad']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openscad/openscad:latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v6

      - name: Checkout jl_scad library
        uses: actions/checkout@v6
        with:
          repository: lijon/jl_scad
          path: libraries/jl_scad

      - name: Checkout BOSL2 library
        uses: actions/checkout@v6
        with:
          repository: BelfrySCAD/BOSL2
          path: libraries/BOSL2

      - name: Install libraries
        run: cp -r libraries /usr/local/share/openscad/

      - name: Create render directory
        run: mkdir render

      - name: Render top half
        run: openscad -D haelfte=TOP -o render/top.3mf -o render/top.stl case.scad

      - name: Render bottom half
        run: openscad -D haelfte=BOT -o render/bot.3mf -o render/bot.stl case.scad

      - name: Upload render artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Servicetastatur-case-${{ github.sha }}
          path: render/*
